// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA40jFbHQ0eneO16Ozjo_wqXPRl1thgjt4',
    appId: '1:395602350653:web:9598f0ee173ee5061f5054',
    messagingSenderId: '395602350653',
    projectId: 'safejourney-2026',
    authDomain: 'safejourney-2026.firebaseapp.com',
    storageBucket: 'safejourney-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqQWxAtYRGdbYqg4S1UhMpQGr33AdSeIc',
    appId: '1:395602350653:android:b714775c984a7d4c1f5054',
    messagingSenderId: '395602350653',
    projectId: 'safejourney-2026',
    storageBucket: 'safejourney-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcI7qVP5pND2jLVgSoePPeIZa8m91H-Iw',
    appId: '1:395602350653:ios:5185f8fc24f4ad921f5054',
    messagingSenderId: '395602350653',
    projectId: 'safejourney-2026',
    storageBucket: 'safejourney-2026.firebasestorage.app',
    iosBundleId: 'com.example.safeJourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcI7qVP5pND2jLVgSoePPeIZa8m91H-Iw',
    appId: '1:395602350653:ios:5185f8fc24f4ad921f5054',
    messagingSenderId: '395602350653',
    projectId: 'safejourney-2026',
    storageBucket: 'safejourney-2026.firebasestorage.app',
    iosBundleId: 'com.example.safeJourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA40jFbHQ0eneO16Ozjo_wqXPRl1thgjt4',
    appId: '1:395602350653:web:9e580e864200d38c1f5054',
    messagingSenderId: '395602350653',
    projectId: 'safejourney-2026',
    authDomain: 'safejourney-2026.firebaseapp.com',
    storageBucket: 'safejourney-2026.firebasestorage.app',
  );
}
